AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  BucketDomainName:
    Type: String
    Description: Regional domain name of the app bucket

Resources:
  # SSL Certificate (must be in us-east-1 for CloudFront)
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # CloudFront Origin Access Control (preferred over OAI)
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: !Sub "Origin Access Control for ${DomainName}"

  # CloudFront Function for Next.js routing
  NextJSRoutingFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: "nextjs-routing"
      FunctionConfig:
        Comment: "Handle Next.js routing for static export"
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
            var request = event.request;
            var uri = request.uri;
            
            // Don't modify requests for static assets
            if (uri.match(/\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map|json|xml|txt)$/i)) {
                return request;
            }
            
            // Handle root path
            if (uri === '/') {
                request.uri = '/index.html';
                return request;
            }
            
            // Handle paths ending with /
            if (uri.endsWith('/')) {
                request.uri = uri + 'index.html';
                return request;
            }
            
            // Handle Next.js routes - add .html if no extension
            if (!uri.includes('.') && !uri.startsWith('/_next/')) {
                request.uri = uri + '.html';
            }
            
            return request;
        }

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        Origins:
          - DomainName: !Ref BucketDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""  # Empty for OAC
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400     # 24 hours
          MaxTTL: 31536000      # 1 year
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt NextJSRoutingFunction.FunctionARN
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2

  # Route53 DNS Records
  DomainDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # This is CloudFront's hosted zone ID
        EvaluateTargetHealth: false

  # WWW Subdomain DNS Record
  WwwDomainDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # This is CloudFront's hosted zone ID
        EvaluateTargetHealth: false

Outputs:
  DistributionId:
    Description: ID of CloudFront distribution
    Value: !Ref CloudFrontDistribution
  DistributionArn:
    Description: ARN of CloudFront distribution
    Value: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
  CloudFrontOriginAccessControl:
    Description: CloudFront Origin Access Control ID
    Value: !Ref CloudFrontOriginAccessControl
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !Sub "https://${DomainName}"
  NextJSFunctionArn:
    Description: ARN of the Next.js routing CloudFront function
    Value: !GetAtt NextJSRoutingFunction.FunctionARN